spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.web: INFO

---
spring:
  profiles: redis
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.springframework.web: DEBUG